// Shared multiplayer rooms for reclaude games: room codes, seats (2–10 players), teams, lobby,
// share links, presence, player names, a turn timer, private per-player data, and four backends.
// Import from a project page with:  import * as rooms from "../shared/rooms.js";
//
// A room is one object at rooms/<CODE> in Firebase Realtime Database:
//   { game, host, seats, min, auto, teams, players: { s0: uid, s1?: uid, … },
//     status: "waiting"|"playing"|"done", turn: <seat>, round, createdAt,
//     board?, winner?: <seat|team> | "draw", line?, last?, left?: <seat>, state?: {…}, online?: { s0?: true, … },
//     again?: { s0?: true, … }, names?: { s0?: "Jun", … }, turnSecs?: <seconds per turn, 0 = no timer>,
//     turnAt?: <ms when the current turn started> }
// Seat keys are "s0".."s9" (not 0..9) so Firebase never turns them into arrays.
// private/<CODE>/s<N> holds one string only that seat's player can read or write (e.g. a hand of cards).
// Access rules: firebase/database.rules.json. Any field a game adds must be allowed there too
// (free-form game data goes in `state`). The rules also enforce who may change what:
//   waiting: the host sets the game up; others may only take an empty seat (filling an auto room starts it).
//            `state` isn't protected yet, so deal hidden or random things in startGame's setup.
//   playing: only the player in seat `turn` may change board/turn/winner/line/last/round/teams/left/state;
//            any seated player may forfeit (quit): status "done", left their own seat, and winner another
//            seat (no teams), the other team (2 teams) or "draw" (3+ players); nothing else changes.
//   done:    the result is fixed; anyone seated may start the next round (round + 1).
//   turn timer: once a turn has run past turnSecs, any seated player may pass it on (skipTurn).
// A taken seat can't be emptied or reassigned, and each player sets only their own online and again flags
// and name (again is cleared when a new round starts). The rules are generated by scripts/rules.mjs.
// Rooms can be deleted by the host while waiting, or by anyone once a day old (createdAt).
//
// Backends all expose:
//   uid, local?, watch(code, cb) → unsubscribe, transact(code, fn) → { committed, value }, removeRoom(code),
//   setAgain(code, seat) (writes only rooms/<code>/again/<seat>: a finished room's other fields are fixed),
//   update(code, fields) (a plain multi-field write; skipTurn and setName use it),
//   watchPrivate(code, seat, cb) → unsubscribe, setPrivate(code, seat, value), clearPrivate(code),
//   presence(code, seat) → stop, online(), offline()
//   topScores(game, n) → [{ uid, name, score }] best first, myScore(game) → entry|null, saveScore(game, name, score)
// transact's fn returns the new room, null to delete it, or undefined to abort. Every backend stamps turnAt
// whenever a write starts a new turn (see stamped), so games don't have to.
// Firebase may call fn with null before it has the room cached: transactions on a room you aren't
// watching (via enter) should return null for a null room, not abort, so Firebase retries with real data.

export const FIREBASE_CONFIG = {
  apiKey: "AIzaSyCCRIEJKgWbghpEhua1HlBvSoAuJ7ffDhE",
  authDomain: "reclaude-67a01.firebaseapp.com",
  databaseURL: "https://reclaude-67a01-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "reclaude-67a01",
  storageBucket: "reclaude-67a01.firebasestorage.app",
  messagingSenderId: "720774301235",
  appId: "1:720774301235:web:d91c1208d791c73b684546",
};
const FIREBASE_VERSION = "10.14.1";
const CODE_CHARS = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no I, O, 0, 1
export const CODE_RE = /^[A-HJ-NP-Z2-9]{4}$/;
export const MAX_SEATS = 10; // scripts/rules.mjs SEATS must match
const IDLE_MS = 60_000; // disconnect after this long in the background
const STALE_MS = 86_400_000; // rooms older than a day may be deleted by anyone (see the rules)
const isStale = (room) => !(room.createdAt > Date.now() - STALE_MS);

export class RoomError extends Error {}

// ---------- seats ----------

export const seatKey = (seat) => `s${seat}`;

// Array of length room.seats: the uid in each seat, or null if empty.
export function seatList(room) {
  return Array.from({ length: room?.seats || 0 }, (_, i) => room.players?.[seatKey(i)] ?? null);
}
export function playerCount(room) {
  return seatList(room).filter(Boolean).length;
}
export function seatOf(room, uid) {
  const i = seatList(room).indexOf(uid);
  return i < 0 ? null : i;
}
// Next occupied seat after `seat`, wrapping around.
export function nextSeat(room, seat) {
  const list = seatList(room);
  for (let k = 1; k <= list.length; k++) {
    const s = (seat + k) % list.length;
    if (list[s]) return s;
  }
  return seat;
}
// Team for a seat: with `teams` set, seats alternate (2 teams: 0,1,0,1…; 3 teams: 0,1,2,0,1,2).
export function teamOf(room, seat) {
  return room.teams ? seat % room.teams : seat;
}
export function isOnline(room, seat) {
  return !!room.online?.[seatKey(seat)];
}
// Has this seat asked to play again (see playAgain)?
export function wantsAgain(room, seat) {
  return !!room.again?.[seatKey(seat)];
}
// The seat's player name, or "P1", "P2"… when they haven't set one.
export function nameOf(room, seat) {
  return room?.names?.[seatKey(seat)] || `P${seat + 1}`;
}
// Seconds left on the current turn, or null when the room has no timer or no game is on.
export function turnLeft(room, now = Date.now()) {
  if (!room?.turnSecs || room.status !== "playing" || typeof room.turnAt !== "number") return null;
  return Math.max(0, Math.ceil((room.turnAt + room.turnSecs * 1000 - now) / 1000));
}

// A write that changes whose turn it is, the round, or starts the game begins a new turn: note when.
// Games often change the room in place, so the old turn, round and status are noted before fn runs.
function stamped(fn) {
  return (cur) => {
    const was = cur && { turn: cur.turn, round: cur.round, status: cur.status };
    const next = fn(cur);
    if (next && next.status === "playing" && (!was || was.turn !== next.turn || was.round !== next.round || was.status !== "playing")) {
      next.turnAt = Date.now();
    }
    return next;
  };
}

// ---------- backends ----------

async function firebaseBackend({ emulator = false } = {}) {
  const base = `https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/`;
  const [appMod, authMod, db$] = await Promise.all([
    import(base + "firebase-app.js"),
    import(base + "firebase-auth.js"),
    import(base + "firebase-database.js"),
  ]);
  const config = emulator
    ? { ...FIREBASE_CONFIG, projectId: "demo-reclaude", databaseURL: "http://127.0.0.1:9000?ns=demo-reclaude-default-rtdb" }
    : FIREBASE_CONFIG;
  const app = appMod.initializeApp(config);
  const auth = authMod.getAuth(app);
  const db = db$.getDatabase(app);
  if (emulator) {
    authMod.connectAuthEmulator(auth, "http://127.0.0.1:9099", { disableWarnings: true });
    db$.connectDatabaseEmulator(db, "127.0.0.1", 9000);
  }
  const user = await new Promise((resolve, reject) => {
    const off = authMod.onAuthStateChanged(auth, (u) => { if (u) { off(); resolve(u); } });
    authMod.signInAnonymously(auth).catch(reject);
  });
  const roomRef = (code, path = "") => db$.ref(db, `rooms/${code}${path}`);
  const privRef = (code, seat) => db$.ref(db, `private/${code}/${seatKey(seat)}`);
  let online = true;
  return {
    uid: user.uid,
    get isOnline() { return online; },
    watch(code, cb) {
      return db$.onValue(roomRef(code), (s) => cb(s.val()), (err) => cb(null, err));
    },
    async transact(code, fn) {
      const r = await db$.runTransaction(roomRef(code), stamped(fn), { applyLocally: false });
      return { committed: r.committed, value: r.snapshot.val() };
    },
    removeRoom(code) {
      return db$.remove(roomRef(code));
    },
    setAgain(code, seat) {
      return db$.set(roomRef(code, `/again/${seatKey(seat)}`), true);
    },
    update(code, fields) {
      const out = {};
      for (const [k, v] of Object.entries(fields)) out[k] = v === SERVER_TIME ? db$.serverTimestamp() : v;
      return db$.update(roomRef(code), out);
    },
    watchPrivate(code, seat, cb) {
      return db$.onValue(privRef(code, seat), (s) => cb(s.val()), (err) => cb(null, err));
    },
    setPrivate(code, seat, value) {
      return db$.set(privRef(code, seat), value);
    },
    clearPrivate(code) {
      return db$.remove(db$.ref(db, `private/${code}`));
    },
    // Marks this player online while connected; Firebase clears it if the connection drops,
    // and it is set again on every reconnect.
    presence(code, seat) {
      const r = roomRef(code, `/online/${seatKey(seat)}`);
      const off = db$.onValue(db$.ref(db, ".info/connected"), (s) => {
        if (s.val() !== true) return;
        db$.onDisconnect(r).remove().then(() => db$.set(r, true)).catch(() => {});
      });
      return () => {
        off();
        db$.onDisconnect(r).cancel().catch(() => {});
        db$.remove(r).catch(() => {});
      };
    },
    async topScores(game, n) {
      const snap = await db$.get(db$.query(db$.ref(db, `scores/${game}`), db$.orderByChild("score"), db$.limitToLast(n)));
      const out = [];
      snap.forEach((c) => { out.push({ uid: c.key, ...c.val() }); });
      return out.reverse();
    },
    async myScore(game) {
      return (await db$.get(db$.ref(db, `scores/${game}/${user.uid}`))).val();
    },
    saveScore(game, name, score) {
      return db$.set(db$.ref(db, `scores/${game}/${user.uid}`), { name, score, at: db$.serverTimestamp() });
    },
    online() { if (!online) { online = true; db$.goOnline(db); } },
    offline() { if (online) { online = false; db$.goOffline(db); } },
  };
}

// Stand-in used by quick automated tests (?backend=fake): tabs in one browser share rooms
// through localStorage and BroadcastChannel. It does not enforce the access rules.
function fakeBackend() {
  const KEY = "rooms-fake-db";
  const channel = new BroadcastChannel("rooms-fake");
  const read = () => JSON.parse(localStorage.getItem(KEY) || '{"rooms":{},"private":{},"scores":{}}');
  const write = (db) => localStorage.setItem(KEY, JSON.stringify(db));
  let uid = sessionStorage.getItem("rooms-fake-uid");
  if (!uid) { uid = "u" + Math.random().toString(36).slice(2, 10); sessionStorage.setItem("rooms-fake-uid", uid); }
  const listeners = new Map(); // "rooms/CODE" or "private/CODE/sN" → Set(cb)
  const present = new Set();   // "CODE/seat" entries this tab keeps online
  let online = true;
  const get = (db, path) => path.split("/").reduce((o, k) => (o == null ? undefined : o[k]), db) ?? null;
  const notify = (path) => {
    const v = get(read(), path);
    for (const cb of listeners.get(path) || []) cb(v === null ? null : structuredClone(v));
  };
  channel.onmessage = (e) => notify(e.data);
  const changed = (path) => { notify(path); channel.postMessage(path); };
  const listen = (path, cb) => {
    if (!listeners.has(path)) listeners.set(path, new Set());
    listeners.get(path).add(cb);
    setTimeout(() => cb(get(read(), path)), 0);
    return () => listeners.get(path).delete(cb);
  };
  const transact = async (code, fn) => {
    const db = read();
    const cur = db.rooms[code] ?? null;
    const next = stamped(fn)(cur === null ? null : structuredClone(cur));
    if (next === undefined) return { committed: false, value: cur };
    if (next === null) delete db.rooms[code]; else db.rooms[code] = next;
    write(db);
    changed(`rooms/${code}`);
    return { committed: true, value: next };
  };
  const flag = (code, seat, on) => transact(code, (room) => {
    if (!room) return undefined;
    room.online = room.online || {};
    if (on) room.online[seatKey(seat)] = true; else delete room.online[seatKey(seat)];
    return room;
  });
  addEventListener("pagehide", () => { for (const k of present) { const [c, s] = k.split("/"); flag(c, +s, false); } });
  return {
    uid,
    fake: true,
    get isOnline() { return online; },
    watch: (code, cb) => listen(`rooms/${code}`, cb),
    transact,
    async removeRoom(code) {
      const db = read();
      delete db.rooms[code];
      write(db);
      changed(`rooms/${code}`);
    },
    setAgain: (code, seat) => transact(code, (room) => { if (!room) return undefined; room.again = { ...(room.again || {}), [seatKey(seat)]: true }; return room; }),
    update: (code, fields) => transact(code, (room) => {
      if (!room) return undefined;
      for (const [k, v] of Object.entries(fields)) {
        const [a, b] = k.split("/");
        const val = v === SERVER_TIME ? Date.now() : v;
        if (b) room[a] = { ...(room[a] || {}), [b]: val }; else room[a] = val;
      }
      return room;
    }),
    watchPrivate: (code, seat, cb) => listen(`private/${code}/${seatKey(seat)}`, cb),
    async clearPrivate(code) {
      const db = read();
      const seats = Object.keys(db.private[code] || {});
      delete db.private[code];
      write(db);
      for (const s of seats) changed(`private/${code}/${s}`);
    },
    async setPrivate(code, seat, value) {
      const db = read();
      db.private[code] = db.private[code] || {};
      db.private[code][seatKey(seat)] = value;
      write(db);
      changed(`private/${code}/${seatKey(seat)}`);
    },
    presence(code, seat) {
      present.add(`${code}/${seat}`);
      if (online) flag(code, seat, true);
      return () => { present.delete(`${code}/${seat}`); flag(code, seat, false); };
    },
    async topScores(game, n) {
      const all = Object.entries(read().scores?.[game] || {}).map(([uid, v]) => ({ uid, ...v }));
      return all.sort((a, b) => b.score - a.score).slice(0, n);
    },
    async myScore(game) {
      return read().scores?.[game]?.[uid] ?? null;
    },
    async saveScore(game, name, score) {
      const db = read();
      db.scores = db.scores || {};
      db.scores[game] = db.scores[game] || {};
      const prev = db.scores[game][uid];
      if (prev && score < prev.score) throw new Error("permission_denied: score can only go up");
      db.scores[game][uid] = { name, score, at: Date.now() };
      write(db);
    },
    online() {
      if (online) return;
      online = true;
      for (const k of present) { const [c, s] = k.split("/"); flag(c, +s, true); }
    },
    offline() {
      if (!online) return;
      online = false;
      for (const k of present) { const [c, s] = k.split("/"); flag(c, +s, false); }
    },
  };
}

// Everyone sharing one device; no network at all. Every seat belongs to "local".
export function localBackend() {
  let room = null;
  let cb = null;
  const priv = {};
  const privCbs = {};
  return {
    uid: "local",
    local: true,
    watch(code, fn) { cb = fn; setTimeout(() => cb && cb(room), 0); return () => { cb = null; }; },
    async transact(code, fn) {
      const next = stamped(fn)(room === null ? null : structuredClone(room));
      if (next === undefined) return { committed: false, value: room };
      room = next;
      if (cb) cb(room === null ? null : structuredClone(room));
      return { committed: true, value: room };
    },
    watchPrivate(code, seat, fn) {
      privCbs[seat] = fn;
      setTimeout(() => privCbs[seat] && privCbs[seat](priv[seat] ?? null), 0);
      return () => { delete privCbs[seat]; };
    },
    async setPrivate(code, seat, value) {
      priv[seat] = value;
      if (privCbs[seat]) privCbs[seat](value);
    },
    async update(code, fields) {
      await this.transact(code, (r) => { for (const [k, v] of Object.entries(fields)) r[k] = v === SERVER_TIME ? Date.now() : v; return r; });
    },
    presence() { return () => {}; },
    online() {},
    offline() {},
  };
}

// ---------- connection ----------

let netPromise = null;
let idleTimer = null;
let inRoom = false;

// Connects on first use (creating or joining), so just opening a game costs no connection.
export function connect() {
  if (!netPromise) {
    const mode = new URLSearchParams(location.search).get("backend");
    netPromise = (mode === "fake" ? Promise.resolve(fakeBackend()) : firebaseBackend({ emulator: mode === "emulator" }))
      .then((b) => { watchVisibility(b); return b; })
      .catch((err) => { netPromise = null; throw err; });
  }
  return netPromise.then((b) => { b.online(); return b; });
}

// Drop the connection after a minute in the background, and whenever the player isn't in a room.
function watchVisibility(b) {
  document.addEventListener("visibilitychange", () => {
    clearTimeout(idleTimer);
    if (document.hidden) idleTimer = setTimeout(() => b.offline(), IDLE_MS);
    else if (inRoom) b.online();
  });
}

// ---------- names ----------
// One name per device, remembered here and written to names/<seat> whenever this player creates or joins a
// room. Names are shown in pages, so < > & are left out (the rules refuse them too); escape names anyway.

const SERVER_TIME = Symbol("server time");
const NAME_KEY = "rooms-name";
export const ROOM_NAME_MAX = 16;
export function cleanRoomName(raw) {
  return String(raw || "").replace(/[<>&]/g, "").replace(/\s+/g, " ").trim().slice(0, ROOM_NAME_MAX).trim();
}
export function myName() {
  try { return cleanRoomName(localStorage.getItem(NAME_KEY)); } catch { return ""; }
}
// Remembers the name on this device and, when in a room, updates it there right away.
export async function setMyName(raw, inRoom = null) {
  const name = cleanRoomName(raw);
  try { if (name) localStorage.setItem(NAME_KEY, name); else localStorage.removeItem(NAME_KEY); } catch {}
  if (inRoom && !inRoom.backend.local && name) await inRoom.backend.update(inRoom.code, { [`names/${seatKey(inRoom.seat)}`]: name });
  return name;
}
const withName = (room, seat) => { const n = myName(); if (n) room.names = { ...(room.names || {}), [seatKey(seat)]: n }; return room; };

// ---------- rooms ----------

function randomCode() {
  return Array.from(crypto.getRandomValues(new Uint8Array(4)), (n) => CODE_CHARS[n % 32]).join("");
}

// Creates a room with a fresh code; the creator is the host in seat 0.
//   seats: maximum players (2–10); min: players needed to start (default: seats);
//   auto: start as soon as every seat is filled (default true; false = host taps Start in a lobby);
//   turnSecs: seconds per turn before the others may skip it (default 0: no timer);
//   makeRoom(): the game's initial fields (board, state, …).
export async function createRoom(game, { seats = 2, min = seats, auto = true, turnSecs = 0, makeRoom = () => ({}) } = {}) {
  if (seats < 2 || seats > MAX_SEATS) throw new RoomError(`Rooms hold 2 to ${MAX_SEATS} players.`);
  const b = await connect();
  for (let attempt = 0; attempt < 6; attempt++) {
    const code = randomCode();
    let stale = false;
    const r = await b.transact(code, (cur) => {
      stale = cur !== null && isStale(cur);
      if (cur !== null) return undefined; // code taken, try another
      return withName({
        turn: 0, round: 0, teams: 0, ...makeRoom(), ...(turnSecs ? { turnSecs } : {}),
        status: "waiting", game, host: b.uid, seats, min, auto, players: { s0: b.uid }, createdAt: Date.now(),
      }, 0);
    });
    if (r.committed) {
      // Hands left from an earlier room with this code must not leak into this one.
      await b.clearPrivate(code).catch(() => {});
      return { backend: b, code, seat: 0 };
    }
    // A day-old room is free to delete: clear it so the code can be used again.
    if (stale) await b.removeRoom(code).catch(() => {});
  }
  throw new RoomError("Couldn't find a free room code. Try again.");
}

// Joins (or rejoins) a room in the first free seat. Returns { backend, code, seat }
// or throws RoomError with a message for players.
export async function joinRoom(game, raw) {
  const code = String(raw || "").trim().toUpperCase();
  if (!CODE_RE.test(code)) throw new RoomError("Room codes are 4 letters or numbers.");
  const b = await connect();
  const current = await new Promise((resolve, reject) => {
    let off = null;
    off = b.watch(code, (v, err) => { setTimeout(() => off && off(), 0); err ? reject(err) : resolve(v); });
  });
  if (!current || isStale(current)) {
    if (current) await b.removeRoom(code).catch(() => {});
    throw new RoomError(`No room called ${code}. Check the code with your friend.`);
  }
  if ((current.game || "tic-tac-toe") !== game || !current.players) throw new RoomError(`${code} is a room for a different game.`);
  const mine = seatOf(current, b.uid);
  if (mine !== null) {
    // Rejoining: bring the name in the room up to date.
    if (myName() && current.names?.[seatKey(mine)] !== myName()) await b.update(code, { [`names/${seatKey(mine)}`]: myName() }).catch(() => {});
    return { backend: b, code, seat: mine };
  }
  if (playerCount(current) >= current.seats) throw new RoomError("That room is full.");
  if (current.status !== "waiting") throw new RoomError("That game has already started.");

  const r = await b.transact(code, (cur) => {
    // Firebase may first call this with an empty local cache. Returning null (not aborting) makes the
    // server reject it and retry with the real room; if the room really is gone, writing null is a no-op.
    if (cur === null) return null;
    if (seatOf(cur, b.uid) !== null || cur.status !== "waiting") return undefined;
    const free = seatList(cur).indexOf(null);
    if (free < 0) return undefined;
    cur.players[seatKey(free)] = b.uid;
    withName(cur, free);
    if (cur.auto && playerCount(cur) === cur.seats) cur.status = "playing";
    return cur;
  });
  if (r.committed && !r.value) throw new RoomError(`No room called ${code}. Check the code with your friend.`);
  const seat = r.value ? seatOf(r.value, b.uid) : null;
  if (seat === null) {
    throw new RoomError(r.value?.status === "waiting" ? "That room is full." : "That game has already started.");
  }
  return { backend: b, code, seat };
}

// Host only: starts a waiting room once enough players are seated. setup(room) prepares the game
// (deal cards, pick teams, …) and returns the room; status becomes "playing".
export async function startGame({ backend, code, seat }, setup = (room) => room) {
  const r = await backend.transact(code, (cur) => {
    // An empty local cache looks like a missing room; returning null lets Firebase retry with the real one
    // (see joinRoom). If the room really is gone, writing null is a no-op.
    if (cur === null) return null;
    if (cur.status !== "waiting" || cur.host !== backend.uid || seat !== 0) return undefined;
    if (playerCount(cur) < (cur.min || cur.seats)) return undefined;
    const next = setup(cur);
    if (!next) return undefined;
    next.status = "playing";
    return next;
  });
  if (r.committed && !r.value) throw new RoomError("That room has closed.");
  if (!r.committed) throw new RoomError("Couldn't start: waiting for more players.");
  return r.value;
}

// Watches a room and keeps this player's presence while they're in it. Returns leave().
export function enter({ backend, code, seat }, onRoom, onGone) {
  inRoom = !backend.local;
  const stopPresence = backend.local ? () => {} : backend.presence(code, seat);
  const unwatch = backend.watch(code, (value, err) => {
    if (err) return onGone("Lost access to the room. Check your connection and try again.");
    if (!value) return onGone(backend.local ? "" : "That room has closed.");
    onRoom(value);
  });
  if (!backend.local) setRoomInUrl(code);
  return function leave() {
    unwatch();
    stopPresence();
    inRoom = false;
    setRoomInUrl(null);
    // Give the presence removal a moment to send, then free the connection.
    if (!backend.local) setTimeout(() => { if (!inRoom) backend.offline(); }, 1500);
  };
}

// Leaves for good, so the others aren't left waiting: the host leaving a waiting room closes it, and a
// game in play is forfeited (status "done", left this seat): the win goes to the other player, or to the
// other team with 2 teams, and with 3 or more players the game ends in a draw. Call it before leave() so
// presence is still valid; errors are ignored (the room may already be gone).
export async function quit({ backend, code, seat }) {
  if (backend.local) return;
  await backend.transact(code, (cur) => {
    if (cur === null) return null;
    if (seatOf(cur, backend.uid) !== seat) return undefined;
    if (cur.status === "waiting") return cur.host === backend.uid ? null : undefined;
    if (cur.status !== "playing") return undefined;
    const others = seatList(cur).flatMap((uid, i) => (uid && i !== seat ? [i] : []));
    if (!others.length) return undefined;
    cur.status = "done";
    cur.winner = cur.teams === 2 ? 1 - (seat % 2) : others.length === 1 && !cur.teams ? others[0] : "draw";
    cur.left = seat;
    return cur;
  }).catch(() => {});
}

// Turn timer: once the current turn has run past turnSecs, any seated player may pass it to the next player.
// The skipped player simply misses that turn. Returns true if the turn was passed on.
export async function skipTurn({ backend, code }, room) {
  if (turnLeft(room) !== 0) return false;
  try {
    await backend.update(code, { turn: nextSeat(room, room.turn), turnAt: SERVER_TIME });
    return true;
  } catch (err) { console.error(err); return false; }
}

// Play again by agreement: marks this seat ready (its own again flag: a finished room's other fields are
// fixed by the rules), and once every other seated player who is online is ready too, starts the next round
// with deal(room, round + 1) (which returns the room set up for the new round, with status "playing").
// Returns "started", "waiting" (others are still deciding) or "none" (the game isn't over).
export async function playAgain({ backend, code, seat }, deal) {
  if (!backend.local) await backend.setAgain(code, seat);
  const r = await backend.transact(code, (cur) => {
    if (cur === null) return null;
    if (cur.status !== "done") return undefined;
    const pending = seatList(cur).some((uid, i) => uid && i !== seat && isOnline(cur, i) && !wantsAgain(cur, i));
    if (pending) return undefined;
    const next = deal(cur, cur.round + 1);
    if (!next) return undefined;
    delete next.again;
    return next;
  });
  if (r.committed && r.value && r.value.status !== "done") return "started";
  return r.value?.status === "done" ? "waiting" : "none";
}

// Builds a same-device room: every seat is filled and the game starts immediately.
export function localRoom(game, players, makeRoom = () => ({})) {
  const backend = localBackend();
  const seats = players;
  const ps = {};
  for (let i = 0; i < seats; i++) ps[seatKey(i)] = "local";
  backend.transact("LOCAL", () => ({
    turn: 0, round: 0, teams: 0, ...makeRoom(),
    status: "playing", game, host: "local", seats, min: seats, auto: true, players: ps, createdAt: Date.now(),
  }));
  return { backend, code: "LOCAL", seat: "local" };
}

// ---------- leaderboards ----------
// Public top-N lists, one entry per player at scores/<game>/<uid>. The rules allow saving only your own
// entry, only upward, at most every 5 seconds, with a 1–12 character name of letters, numbers and spaces.

export const NAME_RE = /^[A-Za-z0-9][A-Za-z0-9 ]{0,11}$/;
export function cleanName(raw) {
  return String(raw || "").replace(/[^A-Za-z0-9 ]/g, "").replace(/\s+/g, " ").trim().slice(0, 12).trim();
}

// Leaderboard calls connect briefly, then let the connection go unless the player is in a room.
async function briefly(fn) {
  const b = await connect();
  try { return await fn(b); } finally { setTimeout(() => { if (!inRoom) b.offline(); }, 1500); }
}
export const topScores = (game, n = 10) => briefly((b) => b.topScores(game, n));
export const myScore = (game) => briefly((b) => b.myScore(game));
export async function saveScore(game, name, score) {
  const clean = cleanName(name);
  if (!NAME_RE.test(clean)) throw new RoomError("Pick a name of up to 12 letters, numbers or spaces.");
  return briefly(async (b) => { await b.saveScore(game, clean, score); return { uid: b.uid, name: clean, score }; });
}
export const myUid = () => briefly((b) => b.uid);

// ---------- links ----------

function setRoomInUrl(code) {
  const url = new URL(location.href);
  if (code) url.searchParams.set("room", code); else url.searchParams.delete("room");
  history.replaceState(null, "", url);
}

export function roomFromUrl() {
  return new URLSearchParams(location.search).get("room");
}

export function shareUrl(code) {
  const url = new URL(location.href);
  const backend = url.searchParams.get("backend");
  url.search = "";
  url.searchParams.set("room", code);
  if (backend) url.searchParams.set("backend", backend);
  return url.toString();
}

export async function share(code, title) {
  const url = shareUrl(code);
  if (navigator.share) {
    try { await navigator.share({ title, text: `Join my game: ${code}`, url }); return "shared"; } catch { return "cancelled"; }
  }
  try { await navigator.clipboard.writeText(url); return "copied"; } catch { return "failed"; }
}

// Test hooks: simulate the idle disconnect without waiting a minute.
export const __test = {
  idleNow: async () => (await netPromise)?.offline(),
  wake: async () => (await netPromise)?.online(),
  isOnline: async () => (netPromise ? (await netPromise).isOnline : null),
  backend: () => netPromise,
};
